# --------------------------------------------------------------------------
# Build variables
#

DISPATCHQUEUE_C_SOURCES := $(wildcard $(DISPATCHQUEUE_SOURCES_DIR)/*.c)

DISPATCHQUEUE_OBJS := $(patsubst $(DISPATCHQUEUE_SOURCES_DIR)/%.c,$(DISPATCHQUEUE_OBJS_DIR)/%.o,$(DISPATCHQUEUE_C_SOURCES))
DISPATCHQUEUE_DEPS := $(DISPATCHQUEUE_OBJS:.o=.d)

DISPATCHQUEUE_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(DISPATCHQUEUE_SOURCES_DIR)

#DISPATCHQUEUE_GENERATE_DEPS = -deps -depfile=$(patsubst $(DISPATCHQUEUE_OBJS_DIR)/%.o,$(DISPATCHQUEUE_OBJS_DIR)/%.d,$@)
DISPATCHQUEUE_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(DISPATCHQUEUE_OBJS): | $(DISPATCHQUEUE_OBJS_DIR)

$(DISPATCHQUEUE_OBJS_DIR):
	$(call mkdir_if_needed,$(DISPATCHQUEUE_OBJS_DIR))

-include $(DISPATCHQUEUE_DEPS)

$(DISPATCHQUEUE_OBJS_DIR)/%.o : $(DISPATCHQUEUE_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(DISPATCHQUEUE_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(DISPATCHQUEUE_GENERATE_DEPS) -o $@ $<
