# --------------------------------------------------------------------------
# Build variables
#

FILESYSTEM_KERNFS_C_SOURCES := $(wildcard $(FILESYSTEM_KERNFS_SOURCES_DIR)/*.c)

FILESYSTEM_KERNFS_OBJS := $(patsubst $(FILESYSTEM_KERNFS_SOURCES_DIR)/%.c,$(FILESYSTEM_KERNFS_OBJS_DIR)/%.o,$(FILESYSTEM_KERNFS_C_SOURCES))
FILESYSTEM_KERNFS_DEPS := $(FILESYSTEM_KERNFS_OBJS:.o=.d)

FILESYSTEM_KERNFS_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(FILESYSTEM_KERNFS_SOURCES_DIR)

#FILESYSTEM_KERNFS_GENERATE_DEPS = -deps -depfile=$(patsubst $(FILESYSTEM_KERNFS_OBJS_DIR)/%.o,$(FILESYSTEM_KERNFS_OBJS_DIR)/%.d,$@)
FILESYSTEM_KERNFS_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(FILESYSTEM_KERNFS_OBJS): | $(FILESYSTEM_KERNFS_OBJS_DIR) $(PRODUCT_DIR)

$(FILESYSTEM_KERNFS_OBJS_DIR):
	$(call mkdir_if_needed,$(FILESYSTEM_KERNFS_OBJS_DIR))

-include $(FILESYSTEM_KERNFS_DEPS)

$(FILESYSTEM_KERNFS_OBJS_DIR)/%.o : $(FILESYSTEM_KERNFS_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(FILESYSTEM_KERNFS_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(FILESYSTEM_KERNFS_GENERATE_DEPS) -o $@ $<
