# --------------------------------------------------------------------------
# Build variables
#

DRIVER_AMIGA_GRAPHICS_C_SOURCES := $(wildcard $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/*.c)
DRIVER_AMIGA_GRAPHICS_ASM_SOURCES := $(wildcard $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/*.s)

DRIVER_AMIGA_GRAPHICS_OBJS := $(patsubst $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/%.c,$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(DRIVER_AMIGA_GRAPHICS_C_SOURCES))
DRIVER_AMIGA_GRAPHICS_DEPS := $(DRIVER_AMIGA_GRAPHICS_OBJS:.o=.d)
DRIVER_AMIGA_GRAPHICS_OBJS += $(patsubst $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/%.s,$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(DRIVER_AMIGA_GRAPHICS_ASM_SOURCES))

DRIVER_AMIGA_GRAPHICS_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)
DRIVER_AMIGA_GRAPHICS_ASM_INCLUDES := $(KERNEL_ASM_INCLUDES) -I$(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)

#DRIVER_AMIGA_GRAPHICS_GENERATE_DEPS = -deps -depfile=$(patsubst $(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.d,$@)
DRIVER_AMIGA_GRAPHICS_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(DRIVER_AMIGA_GRAPHICS_OBJS): | $(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)

$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR):
	$(call mkdir_if_needed,$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR))

-include $(DRIVER_AMIGA_GRAPHICS_DEPS)

$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.o : $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(DRIVER_AMIGA_GRAPHICS_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(DRIVER_AMIGA_GRAPHICS_GENERATE_DEPS) -o $@ $<

$(DRIVER_AMIGA_GRAPHICS_OBJS_DIR)/%.o : $(DRIVER_AMIGA_GRAPHICS_SOURCES_DIR)/%.s
	@echo $<
	@$(AS) $(KERNEL_ASM_CONFIG) $(DRIVER_AMIGA_GRAPHICS_ASM_INCLUDES) $(KERNEL_AS_DONTWARN) -o $@ $<
