# --------------------------------------------------------------------------
# Build variables
#

DRIVER_M68K_AMIGA_HID_C_SOURCES := $(wildcard $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/*.c)
DRIVER_M68K_AMIGA_HID_ASM_SOURCES := $(wildcard $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/*.s)

DRIVER_M68K_AMIGA_HID_OBJS := $(patsubst $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/%.c,$(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.o,$(DRIVER_M68K_AMIGA_HID_C_SOURCES))
DRIVER_M68K_AMIGA_HID_DEPS := $(DRIVER_M68K_AMIGA_HID_OBJS:.o=.d)
DRIVER_M68K_AMIGA_HID_OBJS += $(patsubst $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/%.s,$(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.o,$(DRIVER_M68K_AMIGA_HID_ASM_SOURCES))

DRIVER_M68K_AMIGA_HID_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)
DRIVER_M68K_AMIGA_HID_ASM_INCLUDES := $(KERNEL_ASM_INCLUDES) -I$(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)

#DRIVER_M68K_AMIGA_HID_GENERATE_DEPS = -deps -depfile=$(patsubst $(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.o,$(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.d,$@)
DRIVER_M68K_AMIGA_HID_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(DRIVER_M68K_AMIGA_HID_OBJS): | $(DRIVER_M68K_AMIGA_HID_OBJS_DIR)

$(DRIVER_M68K_AMIGA_HID_OBJS_DIR):
	$(call mkdir_if_needed,$(DRIVER_M68K_AMIGA_HID_OBJS_DIR))

-include $(DRIVER_M68K_AMIGA_HID_DEPS)

$(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.o : $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(DRIVER_M68K_AMIGA_HID_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(DRIVER_M68K_AMIGA_HID_GENERATE_DEPS) -o $@ $<

$(DRIVER_M68K_AMIGA_HID_OBJS_DIR)/%.o : $(DRIVER_M68K_AMIGA_HID_SOURCES_DIR)/%.s
	@echo $<
	@$(AS) $(KERNEL_ASM_CONFIG) $(DRIVER_M68K_AMIGA_HID_ASM_INCLUDES) $(KERNEL_AS_DONTWARN) -o $@ $<
