# --------------------------------------------------------------------------
# Build variables
#

MACHINE_HAL_C_SOURCES := $(wildcard $(MACHINE_HAL_SOURCES_DIR)/*.c)
MACHINE_HAL_ASM_SOURCES := $(wildcard $(MACHINE_HAL_SOURCES_DIR)/*.s)

MACHINE_HAL_OBJS := $(patsubst $(MACHINE_HAL_SOURCES_DIR)/%.c,$(MACHINE_HAL_OBJS_DIR)/%.o,$(MACHINE_HAL_C_SOURCES))
MACHINE_HAL_DEPS := $(MACHINE_HAL_OBJS:.o=.d)
MACHINE_HAL_OBJS += $(patsubst $(MACHINE_HAL_SOURCES_DIR)/%.s,$(MACHINE_HAL_OBJS_DIR)/%.o,$(MACHINE_HAL_ASM_SOURCES))

MACHINE_HAL_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(MACHINE_HAL_SOURCES_DIR)
MACHINE_HAL_ASM_INCLUDES := $(KERNEL_ASM_INCLUDES) -I$(MACHINE_HAL_SOURCES_DIR)

#MACHINE_HAL_GENERATE_DEPS = -deps -depfile=$(patsubst $(MACHINE_HAL_OBJS_DIR)/%.o,$(MACHINE_HAL_OBJS_DIR)/%.d,$@)
MACHINE_HAL_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(MACHINE_HAL_OBJS): | $(MACHINE_HAL_OBJS_DIR)

$(MACHINE_HAL_OBJS_DIR):
	$(call mkdir_if_needed,$(MACHINE_HAL_OBJS_DIR))

-include $(MACHINE_HAL_DEPS)

$(MACHINE_HAL_OBJS_DIR)/%.o : $(MACHINE_HAL_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(MACHINE_HAL_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(MACHINE_HAL_GENERATE_DEPS) -o $@ $<

$(MACHINE_HAL_OBJS_DIR)/%.o : $(MACHINE_HAL_SOURCES_DIR)/%.s
	@echo $<
	@$(AS) $(KERNEL_ASM_CONFIG) $(MACHINE_HAL_ASM_INCLUDES) $(KERNEL_AS_DONTWARN) -o $@ $<
