MEMORY  {
    kernel_rom (rx)  : ORIGIN = 0xfc0000, LENGTH = 128K
}

SECTIONS {
    . = 0xfc0000;

    .text :
        { __text = . ; traps.o(.text) *(.text) __etext = . ; } AT> kernel_rom
    
    .data 0x3000 : AT(LOADADDR(.text) + SIZEOF(.text))
        { __data = . ; *(.data) __edata = . ; } AT> kernel_rom
    
    .bss : AT(LOADADDR(.data) + SIZEOF(.data))
        { __bss = . ; *(.bss) __ebss = . ; } AT> kernel_rom
}
