# --------------------------------------------------------------------------
# Build variables
#

MACHINE_HW_M68K_C_SOURCES := $(wildcard $(MACHINE_HW_M68K_SOURCES_DIR)/*.c)
MACHINE_HW_M68K_ASM_SOURCES := $(wildcard $(MACHINE_HW_M68K_SOURCES_DIR)/*.s)

MACHINE_HW_M68K_OBJS := $(patsubst $(MACHINE_HW_M68K_SOURCES_DIR)/%.c,$(MACHINE_HW_M68K_OBJS_DIR)/%.o,$(MACHINE_HW_M68K_C_SOURCES))
MACHINE_HW_M68K_DEPS := $(MACHINE_HW_M68K_OBJS:.o=.d)
MACHINE_HW_M68K_OBJS += $(patsubst $(MACHINE_HW_M68K_SOURCES_DIR)/%.s,$(MACHINE_HW_M68K_OBJS_DIR)/%.o,$(MACHINE_HW_M68K_ASM_SOURCES))

MACHINE_HW_M68K_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(MACHINE_HW_M68K_SOURCES_DIR)
MACHINE_HW_M68K_ASM_INCLUDES := $(KERNEL_ASM_INCLUDES) -I$(MACHINE_HW_M68K_SOURCES_DIR)

#MACHINE_HW_M68K_GENERATE_DEPS = -deps -depfile=$(patsubst $(MACHINE_HW_M68K_OBJS_DIR)/%.o,$(MACHINE_HW_M68K_OBJS_DIR)/%.d,$@)
MACHINE_HW_M68K_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(MACHINE_HW_M68K_OBJS): | $(MACHINE_HW_M68K_OBJS_DIR)

$(MACHINE_HW_M68K_OBJS_DIR):
	$(call mkdir_if_needed,$(MACHINE_HW_M68K_OBJS_DIR))

-include $(MACHINE_HW_M68K_DEPS)

$(MACHINE_HW_M68K_OBJS_DIR)/%.o : $(MACHINE_HW_M68K_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(MACHINE_HW_M68K_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(MACHINE_HW_M68K_GENERATE_DEPS) -o $@ $<

$(MACHINE_HW_M68K_OBJS_DIR)/%.o : $(MACHINE_HW_M68K_SOURCES_DIR)/%.s
	@echo $<
	@$(AS) $(KERNEL_ASM_CONFIG) $(MACHINE_HW_M68K_ASM_INCLUDES) $(KERNEL_AS_DONTWARN) -o $@ $<
