MEMORY  {
    kernel_rom (rx)  : ORIGIN = 0xfc0000, LENGTH = 128K
}

SECTIONS {
    . = 0xfc0000;

    .text :
        { __text = . ; cpu_vectors_asm.o(CODE) *(CODE) __etext = . ; } AT> kernel_rom
    
    .data 0x3000 : AT(LOADADDR(.text) + SIZEOF(.text))
        { __data = . ; *(DATA) ;
          __class = . ; *(__class) __eclass = . ; __edata = . ; } AT> kernel_rom
    
    .bss : AT(LOADADDR(.data) + SIZEOF(.data))
        { __bss = . ; *(BSS) __ebss = . ; } AT> kernel_rom
}
