# --------------------------------------------------------------------------
# Build variables
#

MACHINE_AMIGA_GRAPHICS_C_SOURCES := $(wildcard $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/*.c)
MACHINE_AMIGA_GRAPHICS_ASM_SOURCES := $(wildcard $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/*.s)

MACHINE_AMIGA_GRAPHICS_OBJS := $(patsubst $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/%.c,$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(MACHINE_AMIGA_GRAPHICS_C_SOURCES))
MACHINE_AMIGA_GRAPHICS_DEPS := $(MACHINE_AMIGA_GRAPHICS_OBJS:.o=.d)
MACHINE_AMIGA_GRAPHICS_OBJS += $(patsubst $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/%.s,$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(MACHINE_AMIGA_GRAPHICS_ASM_SOURCES))

MACHINE_AMIGA_GRAPHICS_C_INCLUDES := $(KERNEL_C_INCLUDES) -I$(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)
MACHINE_AMIGA_GRAPHICS_ASM_INCLUDES := $(KERNEL_ASM_INCLUDES) -I$(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)

#MACHINE_AMIGA_GRAPHICS_GENERATE_DEPS = -deps -depfile=$(patsubst $(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.o,$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.d,$@)
MACHINE_AMIGA_GRAPHICS_GENERATE_DEPS := 


# --------------------------------------------------------------------------
# Build rules
#

$(MACHINE_AMIGA_GRAPHICS_OBJS): | $(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)

$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR):
	$(call mkdir_if_needed,$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR))

-include $(MACHINE_AMIGA_GRAPHICS_DEPS)

$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.o : $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/%.c
	@echo $<
	@$(CC) $(KERNEL_CC_CONFIG) $(CC_KOPT_SETTING) $(CC_GEN_DEBUG_INFO) $(KERNEL_CC_PREPROC_DEFS) $(MACHINE_AMIGA_GRAPHICS_C_INCLUDES) $(KERNEL_CC_DONTWARN) $(MACHINE_AMIGA_GRAPHICS_GENERATE_DEPS) -o $@ $<

$(MACHINE_AMIGA_GRAPHICS_OBJS_DIR)/%.o : $(MACHINE_AMIGA_GRAPHICS_SOURCES_DIR)/%.s
	@echo $<
	@$(AS) $(KERNEL_ASM_CONFIG) $(MACHINE_AMIGA_GRAPHICS_ASM_INCLUDES) $(KERNEL_AS_DONTWARN) -o $@ $<
